version: '3.8'

services:
  frontend:
    build: ./my-react-app
    ports:
      - "3000:3000"
    # image: seoga9/frontend-image:v1
    depends_on:
      - backend  # 백엔드 서비스가 준비되면 프론트엔드 서비스 실행

  backend:
    build: ./myapi
    # image: seoga9/backend-image:v1
    ports:
      - "8000:8000"  # 호스트 포트와 컨테이너 포트 매핑 예시
    environment:
      - DATABASE_URL=mysql+pymysql://kitri:rive123@db:3306/rive  # 데이터베이스 연결 정보 설정
    depends_on:
      - db  # 데이터베이스 서비스가 준비되면 백엔드 서비스 실행

  db:
    image: mysql:8.0
    container_name: rive_db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: rive
      MYSQL_USER: kitri
      MYSQL_PASSWORD: rive123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# networks:

volumes:
  db_data:
